name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -r app/requirements.txt
      - run: pip install pytest
      - run: python -m pytest -q tests/ -vv

  build-and-push:
    needs: ci
    if: ${{ needs.ci.result == 'success' && ( (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-docker-app:latest

  deploy:
    needs: build-and-push
    if: ${{ needs.build-and-push.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy va aquí"

